import { addErrorHandler, setNormalizationHandler } from "./json-schema-errors.js";

// Normalization Handlers
import allOfNormalizationHandler from "./normalization-handlers/allOf.js";
import anyOfNormalizationHandler from "./normalization-handlers/anyOf.js";
import constNormalizationHandler from "./normalization-handlers/const.js";
import definitionsNormalizationHandler from "./normalization-handlers/definitions.js";
import dependentRequiredNormalizationHandler from "./normalization-handlers/dependentRequired.js";
import dynamicRefNormalizationHandler from "./normalization-handlers/dynamicRef.js";
import elseNormalizationHandler from "./normalization-handlers/else.js";
import enumNormalizationHandler from "./normalization-handlers/enum.js";
import exclusiveMaximumNormalizationHandler from "./normalization-handlers/exclusiveMaximum.js";
import exclusiveMinimumNormalizationHandler from "./normalization-handlers/exclusiveMinimum.js";
import formatNormalizationHandler from "./normalization-handlers/format.js";
import ifNormalizationHandler from "./normalization-handlers/if.js";
import maximumNormalizationHandler from "./normalization-handlers/maximum.js";
import maxItemsNormalizationHandler from "./normalization-handlers/maxItems.js";
import maxLengthNormalizationHandler from "./normalization-handlers/maxLength.js";
import maxPropertiesNormalizationHandler from "./normalization-handlers/maxProperties.js";
import minimumNormalizationHandler from "./normalization-handlers/minimum.js";
import minItemsNormalizationHandler from "./normalization-handlers/minItems.js";
import minLengthNormalizationHandler from "./normalization-handlers/minLength.js";
import minPropertiesNormalizationHandler from "./normalization-handlers/minProperties.js";
import multipleOfNormalizationHandler from "./normalization-handlers/multipleOf.js";
import notNormalizationHandler from "./normalization-handlers/not.js";
import oneOfNormalizationHandler from "./normalization-handlers/oneOf.js";
import patternNormalizationHandler from "./normalization-handlers/pattern.js";
import propertiesNormalizationHandler from "./normalization-handlers/properties.js";
import refNormalizationHandler from "./normalization-handlers/ref.js";
import requiredNormalizationHandler from "./normalization-handlers/required.js";
import thenNormalizationHandler from "./normalization-handlers/then.js";
import typeNormalizationHandler from "./normalization-handlers/type.js";
import uniqueItemsNormalizationHandler from "./normalization-handlers/uniqueItems.js";

// Error Handlers
import anyOfErrorHandler from "./error-handlers/anyOf.js";
import booleanSchemaErrorHandler from "./error-handlers/boolean-schema.js";
import constErrorHandler from "./error-handlers/const.js";
import dependentRequiredErrorHandler from "./error-handlers/dependentRequired.js";
import enumErrorHandler from "./error-handlers/enum.js";
import exclusiveMaximumErrorHandler from "./error-handlers/exclusiveMaximum.js";
import exclusiveMinimumErrorHandler from "./error-handlers/exclusiveMinimum.js";
import formatErrorHandler from "./error-handlers/format.js";
import maximumErrorHandler from "./error-handlers/maximum.js";
import maxItemsErrorHandler from "./error-handlers/maxItems.js";
import maxLengthErrorHandler from "./error-handlers/maxLength.js";
import maxPropertiesErrorHandler from "./error-handlers/maxProperties.js";
import minimumErrorHandler from "./error-handlers/minimum.js";
import minItemsErrorHandler from "./error-handlers/minItems.js";
import minLengthErrorHandler from "./error-handlers/minLength.js";
import minPropertiesErrorHandler from "./error-handlers/minProperties.js";
import multipleOfErrorHandler from "./error-handlers/multipleOf.js";
import notErrorHandler from "./error-handlers/not.js";
import oneOfErrorHandler from "./error-handlers/oneOf.js";
import patternErrorHandler from "./error-handlers/pattern.js";
import requiredErrorHandler from "./error-handlers/required.js";
import typeErrorHandler from "./error-handlers/type.js";
import uniqueItemsErrorHandler from "./error-handlers/uniqueItems.js";

setNormalizationHandler("https://json-schema.org/keyword/allOf", allOfNormalizationHandler);
setNormalizationHandler("https://json-schema.org/keyword/anyOf", anyOfNormalizationHandler);
setNormalizationHandler("https://json-schema.org/keyword/const", constNormalizationHandler);
setNormalizationHandler("https://json-schema.org/keyword/definitions", definitionsNormalizationHandler);
setNormalizationHandler("https://json-schema.org/keyword/dependentRequired", dependentRequiredNormalizationHandler);
setNormalizationHandler("https://json-schema.org/keyword/draft-2020-12/dynamicRef", dynamicRefNormalizationHandler);
setNormalizationHandler("https://json-schema.org/keyword/else", elseNormalizationHandler);
setNormalizationHandler("https://json-schema.org/keyword/enum", enumNormalizationHandler);
setNormalizationHandler("https://json-schema.org/keyword/draft-2020-12/format", formatNormalizationHandler);
setNormalizationHandler("https://json-schema.org/keyword/draft-2020-12/format-assertion", formatNormalizationHandler);
setNormalizationHandler("https://json-schema.org/keyword/draft-2019-09/format", formatNormalizationHandler);
setNormalizationHandler("https://json-schema.org/keyword/draft-2019-09/format-assertion", formatNormalizationHandler);
setNormalizationHandler("https://json-schema.org/keyword/draft-07/format", formatNormalizationHandler);
setNormalizationHandler("https://json-schema.org/keyword/draft-06/format", formatNormalizationHandler);
setNormalizationHandler("https://json-schema.org/keyword/draft-04/format", formatNormalizationHandler);
setNormalizationHandler("https://json-schema.org/keyword/if", ifNormalizationHandler);
setNormalizationHandler("https://json-schema.org/keyword/exclusiveMaximum", exclusiveMaximumNormalizationHandler);
setNormalizationHandler("https://json-schema.org/keyword/exclusiveMinimum", exclusiveMinimumNormalizationHandler);
setNormalizationHandler("https://json-schema.org/keyword/maximum", maximumNormalizationHandler);
setNormalizationHandler("https://json-schema.org/keyword/maxItems", maxItemsNormalizationHandler);
setNormalizationHandler("https://json-schema.org/keyword/maxLength", maxLengthNormalizationHandler);
setNormalizationHandler("https://json-schema.org/keyword/maxProperties", maxPropertiesNormalizationHandler);
setNormalizationHandler("https://json-schema.org/keyword/minimum", minimumNormalizationHandler);
setNormalizationHandler("https://json-schema.org/keyword/minItems", minItemsNormalizationHandler);
setNormalizationHandler("https://json-schema.org/keyword/minLength", minLengthNormalizationHandler);
setNormalizationHandler("https://json-schema.org/keyword/minProperties", minPropertiesNormalizationHandler);
setNormalizationHandler("https://json-schema.org/keyword/multipleOf", multipleOfNormalizationHandler);
setNormalizationHandler("https://json-schema.org/keyword/not", notNormalizationHandler);
setNormalizationHandler("https://json-schema.org/keyword/oneOf", oneOfNormalizationHandler);
setNormalizationHandler("https://json-schema.org/keyword/pattern", patternNormalizationHandler);
setNormalizationHandler("https://json-schema.org/keyword/properties", propertiesNormalizationHandler);
setNormalizationHandler("https://json-schema.org/keyword/ref", refNormalizationHandler);
setNormalizationHandler("https://json-schema.org/keyword/required", requiredNormalizationHandler);
setNormalizationHandler("https://json-schema.org/keyword/then", thenNormalizationHandler);
setNormalizationHandler("https://json-schema.org/keyword/type", typeNormalizationHandler);
setNormalizationHandler("https://json-schema.org/keyword/uniqueItems", uniqueItemsNormalizationHandler);

addErrorHandler(anyOfErrorHandler);
addErrorHandler(booleanSchemaErrorHandler);
addErrorHandler(constErrorHandler);
addErrorHandler(dependentRequiredErrorHandler);
addErrorHandler(enumErrorHandler);
addErrorHandler(exclusiveMaximumErrorHandler);
addErrorHandler(exclusiveMinimumErrorHandler);
addErrorHandler(formatErrorHandler);
addErrorHandler(maximumErrorHandler);
addErrorHandler(maxItemsErrorHandler);
addErrorHandler(maxLengthErrorHandler);
addErrorHandler(maxPropertiesErrorHandler);
addErrorHandler(minimumErrorHandler);
addErrorHandler(minItemsErrorHandler);
addErrorHandler(minLengthErrorHandler);
addErrorHandler(minPropertiesErrorHandler);
addErrorHandler(multipleOfErrorHandler);
addErrorHandler(notErrorHandler);
addErrorHandler(oneOfErrorHandler);
addErrorHandler(patternErrorHandler);
addErrorHandler(requiredErrorHandler);
addErrorHandler(typeErrorHandler);
addErrorHandler(uniqueItemsErrorHandler);

export { addErrorHandler, jsonSchemaErrors, setNormalizationHandler } from "./json-schema-errors.js";
